version: '3.7'
services:
  order-database:
    container_name: order-postgresql-database
    image: postgres:11.5-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=order
    expose:
      - 5432

  order:
    container_name: order
    build:
      context: .
      args:
        - APP_NAME=order
        - APP_VERSION=0.0.1
    ports:
      - 8080:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
