version: '3.7'
services:

########################## DEVELOPER ##########################
  developer-postgresql:
    container_name: developer-postgresql
    image: postgres:11.5-alpine
    ports: # Map container port 5432 to host port 5433
      - 5433:5432
    environment:
      - POSTGRES_DB=developer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=

  developer:
    container_name: developer
    build:
      context: developer
      args:
        - APP_NAME=developer
        - APP_VERSION=0.0.1
    ports:
      - 8090:8090

  ########################## ORDER ##########################
  order-postgresql:
    container_name: order-postgresql
    image: postgres:11.5-alpine
    ports: # Map container port 5432 to host port 5434
      - 5434:5432
    environment:
      - POSTGRES_DB=order
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=

  order:
    container_name: order
    build:
      context: order
      args:
        - APP_NAME=order
        - APP_VERSION=0.0.1
    ports:
      - 8091:8091