version: "3.7"
services:
  ########################## DEVELOPER INFORMATION ##########################
  developer-information-mongodb:
    container_name: developer-information-mongodb
    image: mongo:4.2.5
    restart: always
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  # Allow to create collection and insert data at start
  mongo-seed:
    build:
      context: mongo

  developer-information:
    container_name: developer-information
    image: veben/developer-information:latest # Image from Docker hub
    ports:
      - 8092:8092
