database:
  host: order-postgresql
  port: 5432
  username: postgres
  password:

spring:
  jpa:
    show-sql: true
  datasource:
    data: classpath:data/data-local.sql
    initialization-mode: always