server:
  port: 8091

spring:
  application:
    name: order

  datasource:
    url: jdbc:postgresql://${database.host}:${database.port}/order
    username: ${database.username}
    password: ${database.password}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"