spring:
  application:
    name: order

  # PostgreSQL
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"