database:
  host: developer-postgresql
  port: 5432
  username: postgres
  password:

developer-information:
  host: developer-information

spring:
  jpa:
    show-sql: true
  datasource:
    data: classpath:data/data-local.sql
    initialization-mode: always
