database:
  host: localhost
  port: 5433
  username: postgres
  password:

developer-information:
  host: localhost

spring:
  jpa:
    show-sql: true
  datasource:
    data: classpath:data/data-local.sql
    initialization-mode: always
