server:
  port: 8090

spring:
  application:
    name: developer

  datasource:
    url: jdbc:postgresql://${database.host}:${database.port}/${spring.application.name}
    username: ${database.username}
    password: ${database.password}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Application
application:
  protocol: http
  host: localhost
