name: Developer-information-CI

on:
  push:
    branches: [master]

env:
  host-vm: ubuntu-latest
  service-folder: developer
  java-version: 14

jobs:
  test:
    runs-on: ${{env.host-vm}}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{env.java-version}}

      - name: Verify with Maven
        working-directory: ./${{env.service-folder}}
        run: mvn -B verify

  package:
    runs-on: ${{env.host-vm}}
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{env.java-version}}

      - name: Package
        working-directory: ./${{env.service-folder}}
        run: mvn -B package

  upload-jar:
    runs-on: ${{env.host-vm}}
    needs: package
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v1
        with:
          name: Upload jar
          path: ./${{env.service-folder}}