name: Developer-CI

on:
  push:
    branches: [master]

env:
  service-folder: developer
  java-version: 14

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: ${{env.java-version}}

      - name: Package
        working-directory: ./${{env.service-folder}}
        run: mvn -B clean package

  upload-jar:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - uses: actions/upload-artifact@v1
        with:
          name: Upload jar
          path: ./${{env.service-folder}}

  build-n-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - uses: docker/build-push-action@v1
        env:
            DOCKER_BUILDKIT: 1
        with:
          build_args: APP_NAME=developer,APP_VERSION=0.0.1
          path: ./${{env.service-folder}}
          repository: veben/developer
          tags: latest
