name: MS-front-CI

on:
  push:
    branches: [master]

env:
  host-vm: ubuntu-latest
  service-folder: ms-front
  node-version: 13.5

jobs:
  test:
    runs-on: ${{env.host-vm}}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.node-version}}

      - name: Install Angular CLI
        working-directory: ./${{env.service-folder}}
        run: npm install @angular/cli

      - name: Test with npm
        working-directory: ./${{env.service-folder}}
        run: npm run test:ci

  package:
    runs-on: ${{env.host-vm}}
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{env.node-version}}

      - name: Install dependencies
        working-directory: ./${{env.service-folder}}
        run: npm install

      - name: Build
        working-directory: ./${{env.service-folder}}
        run: npm run build:prod

  upload-sources:
    runs-on: ${{env.host-vm}}
    needs: package
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v1
        with:
          name: Upload sources
          path: ./${{env.service-folder}}
