name: MS-front-CI

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.5

      - name: Install Angular CLI
        working-directory: ./ms-front
        run: npm install @angular/cli

      - name: Test with npm
        working-directory: ./ms-front
        run: npm run test:ci
