name: MS-front-CI

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.5

      - name: Install Angular CLI
        working-directory: ./ms-front
        run: npm install @angular/cli

      - name: Test with npm
        working-directory: ./ms-front
        run: npm run test:ci

  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          java-version: 13.5

      - name: Install dependencies
        working-directory: ./ms-front
        run: npm install

      - name: Build
        working-directory: ./ms-front
        run: npm run build:prod

  upload-sources:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v1
        with:
          name: Upload sources
          path: ./ms-front
