name: MS-front-CI

on:
  push:
    branches:
      - "master"
      - "feature/**"

env:
  service-name: ms-front
  node-version: 14.15.3

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}

      - name: Install Angular CLI
        working-directory: ./${{ env.service-name }}
        run: npm install @angular/cli

      - name: Test with npm
        working-directory: ./${{ env.service-name }}
        run: npm run test:ci

  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}

      - name: Install dependencies
        working-directory: ./${{ env.service-name }}
        run: npm install

      - name: Build
        working-directory: ./${{ env.service-name }}
        run: npm run build:prod

      - name: Upload generated content
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.service-name }}
          path: ${{ env.service-name }}/dist/

      - name: Upload Dockerfile
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.service-name }}
          path: ${{ env.service-name }}/Dockerfile

  build-n-push-image:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: ${{ env.service-name }}

      - uses: docker/build-push-action@v1
        env:
          DOCKER_BUILDKIT: 1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: veben/${{ env.service-name }}
          build_args: APP_NAME=${{ env.service-name }}
          path: ./${{ env.service-name }}
          tags: latest
